@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam DefaultFontName Courier

title "Data Processing and Bias Mitigation Workflow"

Container(datacollection, "Data Collection", "Aggregation of datasets in various formats\nincluding text, CSV, and XLRD.")

System_Boundary(app,"Model") {
    Container(datapreprocessing, "Data Preprocessing", "Preprocessing involves cleaning and organizing\nraw data to prepare it for machine learning model training.")
    Container(datavisualization, "Data Visualization", "Visualization techniques are employed to analyze\nthe distribution of data, identify outliers, and detect class imbalances.")
    Container(biasmitigation, "Bias Mitigation", "Mitigation strategies are applied to eliminate or reduce\nbiases such as Selection bias, Measurement bias, etc.")
}

Container(model, "Machine Learning Model", "A program designed to identify patterns\nand make decisions based on previously unseen datasets.")

System_Ext(result, "Balanced datasets, Reduced disparities,\nImproved fairness metrics")

Rel_R(datacollection, datapreprocessing, "Send the raw datasets to preprocessing")
Rel_D(datapreprocessing, datavisualization, "Send the processed data to data visualization")
Rel_D(datavisualization, biasmitigation, "Send the dataset to bias mitigation")
Rel_L(biasmitigation, model, "Send the resultant datasets to model\nto assess if biases are effectively reduced")

Rel(model, result, "Yes")

@enduml